image: node:16-stretch

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache

pages: 
  artifacts: 
    paths: 
      - builds
      - build
      - node_modules/
      - .yarn
      - .yarn/
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - .yarn/
      - .yarn-cache/
      - .yarn
      - .yarn.lock
  only: 
    - main
  script: 
    - yarn install
    - yarn build
  stage: deploy