image: node:14-stretch

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn/
      - yarn.lock
pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main
