image: node:16-stretch

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn/
      - yarn.lock
pages: 
  artifacts: 
    paths: 
      - builds
      - build
      - node_modules/
      - .yarn
      - .yarn/
  cache: 
    paths: 
      - .yarn-cache/
  only: 
    - master
  script: 
    - yarn build
  stage: deploy