image: node:14-stretch

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn/
      - yarn.lock
pages: 
  artifacts: 
    paths: 
      - build
  cache: 
    paths: 
      - .yarn-cache/
  only: 
    - master
  script: 
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 3.2.4
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn config set cache-folder $(pwd)/.yarn-cache
    - yarn install
    - yarn build
  stage: deploy
