image: node:9.4.0

before_script:
  - yarn install --cache-folder .yarn

pages:
  stage: test
  cache:
      paths:
        - node_modules/
        - .yarn/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH